env:
  browser: true
  es2021: true
extends:
  - plugin:react/recommended
  - airbnb
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
rules: {
  react/prop-types: off,
  react/jsx-one-expression-per-line: off,
  jsx-a11y/click-events-have-key-events: off,
  jsx-a11y/no-noninteractive-element-interactions: off
}
